CREATE TABLE `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(32) NOT NULL,
  `email` VARCHAR(264) NOT NULL,
  `verified` INT(11) NOT NULL COMMENT '0=no, 1=yes',
  `verification_code` VARCHAR(264) NOT NULL,
  `created` datetime NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=134 ;